### ISSUE TITLE
Atlas-PDF-export only as single file possible

### ISSUE THREAD

**Issue by Nane231** [DelazJ/MapsPrinter#39] opened 2020-09-15 05:43 UTC
First I want to say, that this plugin is very helpful!! And I don't know if it is a bug or it should be like this: If I print an Atlas as pdf and I Do NOT select the possibility "single file export when possible", I get different results with the MapsPrinter or printing in QGIS. Right from Qgis I get for each Atlas-feature one pdf with the name given in "Output filename expression". When I print the pdf with the MapPrinter I get only one PDF-file with all the features-pages and it named like the layout.
Can I print with the MapsPrinter a PDF-file for each Atlas-feature instead a single file for all together?

**Comment by DelazJ** [comment] 2021-07-02 13:50
Hi,
Quite a late reply, but yes you can export a single pdf file for each feature or a single pdf file for all. Depends on your choice, like if you were exporting from QGIS. No difference.
I tried and couldn't reproduce your issue. Closing. Thanks.

**Closed as completed by DelazJ** 2021-07-02 13:50 UTC

**Comment by Nane231** [comment] 2021-08-23 08:10
Hi,
thank you for your effort! I just noticed that I worked with an old version of MapPrinter. With the version 0.5.1 I had the difficulties, but now with the version 0.8 everything is fine! Thank you for the helpful plugin!
