### ISSUE TITLE
Export in PDF change police's size

### ISSUE THREAD

**Issue by GlaDal** [DelazJ/MapsPrinter#8] opened 2015-10-06 06:42 UTC
Hi,

When I export composers from maps printer in PDF, It change the police's size of graticule (from 8 to 4 I think). It happened from two differents pc with qgis 2.8.3.

Thanks,

Bye, 

Gladal

**Comment by DelazJ** [comment] 2015-10-06 16:58
Hi Gladal,
Are you talking about the coordinates texts shown when using the grid around a map frame? If so, I can not reproduce your issue.
Can you check if exporting directly from Print composer does export with the right font size?
Thanks,
DelazJ

**Comment by GlaDal** [comment] 2015-10-07 10:06
Hi !
"Are you talking about the coordinates texts shown when using the grid around a map frame?".
Yes, that's it !
I checked on several projects and I have the same problem. Exports in PDF from the print composer are good. Exports are in vector.
Thanks !

Gladal

**Comment by GlaDal** [comment] 2015-10-14 16:04
Hi,

Have you find any solutions about the problem ?

Thanks
Have a nice day

Gladal

**Comment by DelazJ** [comment] 2015-10-14 16:52
Hi,
Sorry. I hadn't time to dig this issue. Would you mind giving me the OS and qgis version (32 or 64 bits) u use?
Meanwhile, can you download the [v0.3 release](https://github.com/DelazJ/MapsPrinter/releases/tag/v0.3) and test if the bug occurs, please?
Thanks

**Comment by GlaDal** [comment] 2015-10-22 12:05
Hi,
I'm working on windows 64bits (so qgis 64bits also)
I'm downloading the last version and I will try again (after holidays ! :-)

Thanks for all

Gladal

**Comment by GlaDal** [comment] 2015-11-10 12:26
HI !
I've just tested with the last version (0.3), and I've the same problem but not only with the graticule text, labels from a shp have been reduced to 1mm ! :-(

![b3_site_01](https://cloud.githubusercontent.com/assets/7015197/11062367/a1e8c8a8-87ae-11e5-920a-3d926d25ca48.jpg)

**Comment by mirouml** [comment] 2015-11-11 01:43
There are actually more problems. I had to stop using this updated plugin and going back to old version because exporting to PDF doesn't properly work anymore. Please see attached image of standard PDF export vs Maps Printer export:

![pdf_vs_pdfmp](https://cloud.githubusercontent.com/assets/8064130/11081554/5e6923c8-8869-11e5-84b4-3035791819bc.PNG)

**Comment by DelazJ** [comment] 2015-11-12 12:21
Thanks for your reports. Would you mind sending me a project that i can test (with the settings you use on print composer and layers)?

**Comment by GlaDal** [comment] 2015-11-13 08:22
Hi !

Can you send me you email ? I will send you a project.

Thanks for all !

**Comment by DelazJ** [comment] 2015-11-13 12:53
delazj at gmail dot com

**Comment by mirouml** [comment] 2015-11-13 23:19
Hi, unfortunately I can't send the project due to data copyrights but I am sure you can easily replicate the issues:
1. the green polygon - using shape burst fill with 70% transparency
2. the thin gray/black lines - using 0.05 line thickness and 50% transparency

Thank you for care and this great plugin.

**Comment by MarHoff** [comment] 2016-10-21 13:52
> 1. the green polygon - using shape burst fill with 70% transparency
> 2. the thin gray/black lines - using 0.05 line thickness and 50% transparency

I got same sort of errors here. However it's seems mainly due to transparency being yet not fully supported by QGIS vector PDF output.

Your plugin don't seem to respect the "Print as Raster" setting of the composition. It would be a nice update if you could check against this setting to output "raster PDF" as the QGIS composer have this build-in capacity.

![bug maps printer export raster](https://cloud.githubusercontent.com/assets/4598589/19600646/46f9e162-97a6-11e6-98ac-381011d7c825.png)

**Comment by DelazJ** [comment] 2021-07-14 08:13
This issue should be fixed in recent versions. Closing...

**Closed as completed by DelazJ** 2021-07-14 08:13 UTC
